
namespace ErrorHandlerEngine.ModelObjecting
{
    /// <summary>
    /// Type: Copy of System.__HResults
    /// Assembly: mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
    /// MVID: A638AB13-AAFE-4F3B-A87D-581950AD2C45
    /// Assembly location: C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll
    /// </summary>
    public enum ExceptionTypes
    {
        InternalLoggerException
        ,
        InvalidToolsetDefinitionException
            ,
        RemoteErrorException
            ,
        BuildAbortedException
            ,
        InvalidProjectFileException
            ,
        LoggerException
            ,
        RuntimeBinderException
            ,
        RuntimeBinderInternalCompilerException
            ,
        CmdLineException
            ,
        ParserException
            ,
        IncompleteInitialization
            ,
        InstanceUpdateException
            ,
        SourceExpressionException
            ,
        LambdaSerializationException
            ,
        InvalidWorkflowException
            ,
        AttributeTableValidationException
            ,
        VersionMismatchException
            ,
        WorkflowApplicationException
            ,
        AddInSegmentDirectoryNotFoundException
            ,
        InvalidPipelineStoreException
            ,
        AggregateException
            ,
        ApplicationException
            ,
        CompositionContractMismatchException
            ,
        CompositionException
            ,
        ImportCardinalityMismatchException
            ,
        ComposablePartException
            ,
        ValidationException
            ,
        ExceptionCollection
            ,
        ProviderException
            ,
        SettingsPropertyIsReadOnlyException
            ,
        SettingsPropertyNotFoundException
            ,
        SettingsPropertyWrongTypeException
            ,
        ChangeConflictException
            ,
        EventLogException
            ,
        EventSourceException
            ,
        ActiveDirectoryObjectExistsException
            ,
        ActiveDirectoryObjectNotFoundException
            ,
        ActiveDirectoryOperationException
            ,
        ActiveDirectoryServerDownException
            ,
        DirectoryException
            ,
        AsynchronousOperationException
            ,
        MetadataSerializationException
            ,
        WSTrustSerializationException
            ,
        RequestException
            ,
        CardSpaceException
            ,
        IdentityValidationException
            ,
        PolicyValidationException
            ,
        ServiceBusyException
            ,
        ServiceNotStartedException
            ,
        StsCommunicationException
            ,
        UnsupportedPolicyOptionsException
            ,
        UntrustedRecipientException
            ,
        UserCancellationException
            ,
        FederatedAuthenticationSessionEndingException
            ,
        FederationException
            ,
        WSFederationMessageException
            ,
        InvalidTimeZoneException
            ,
        IsolatedStorageException
            ,
        SequenceFullException
            ,
        InstrumentationBaseException
            ,
        WmiProviderInstallationException
            ,
        HttpRequestException
            ,
        SmtpException
            ,
        PeerToPeerException
            ,
        RuntimeWrappedException
            ,
        InstancePersistenceException
            ,
        SUDSGeneratorException
            ,
        SUDSParserException
            ,
        InvalidDataContractException
            ,
        RightsManagementException
            ,
        InvalidChannelBindingException
            ,
        SystemException
            ,
        BarrierPostPhaseException
            ,
        LockRecursionException
            ,
        TaskSchedulerException
            ,
        TimeZoneNotFoundException
            ,
        ParseException
            ,
        MembershipCreateUserException
            ,
        MembershipPasswordException
            ,
        ViewStateException
            ,
        EntityDataSourceValidationException
            ,
        LinqDataSourceValidationException
            ,
        NoClickablePointException
            ,
        ProxyAssemblyNotLoadedException
            ,
        PrintDialogException
            ,
        InvalidActiveXStateException
            ,
        XpsException
            ,
        XpsWriterException
            ,
        RuleException
            ,
        WorkflowValidationFailedException
            ,
        WorkflowMarkupSerializationException
            ,
        WorkflowTerminatedException
            ,
        WorkflowOwnershipException
            ,
        XamlException
            ,
        SqlException
            ,
        AppDomainUnloadedException
            ,
        ArgumentException
            ,
        ArgumentOutOfRangeException
            ,
        ArithmeticException
            ,
        ArrayTypeMismatchException
            ,
        BadImageFormatException
            ,
        COMEmulateException
            ,
        ContextMarshalException
            ,
        CoreException
            ,
        CryptographicException
            ,
        DirectoryNotFoundException
            ,
        DivideByZeroException
            ,
        DuplicateWaitObjectException
            ,
        EndOfStreamException
            ,
        EntryPointNotFoundException
            ,
        Exception
            ,
        ExecutionEngineException
            ,
        FieldAccessException
            ,
        FileNotFoundException
            ,
        FormatException
            ,
        IndexOutOfRangeException
            ,
        InvalidCastException
            ,
        InvalidComObjectException
            ,
        InvalidFilterCriteriaException
            ,
        InvalidOleVariantTypeException
            ,
        InvalidOperationException
            ,
        IOException
            ,
        AccessException
            ,
        MethodAccessException
            ,
        MissingFieldException
            ,
        MissingManifestResourceException
            ,
        MissingMemberException
            ,
        MissingMethodException
            ,
        MulticastNotSupportedException
            ,
        NotFiniteNumberException
            ,
        NotImplementedException
            ,
        NotSupportedException
            ,
        NullReferenceException
            ,
        OutOfMemoryException
            ,
        OverflowException
            ,
        PathTooLongException
            ,
        RankException
            ,
        ReflectionTypeLoadException
            ,
        RemotingException
            ,
        SafeArrayTypeMismatchException
            ,
        SecurityException
            ,
        SerializationException
            ,
        StackOverflowException
            ,
        SynchronizationLockException
            ,
        TargetException
            ,
        TargetInvocationException
            ,
        TargetParameterCountException
            ,
        ThreadAbortException
            ,
        ThreadInterruptedException
            ,
        ThreadStateException
            ,
        ThreadStopException
            ,
        TypeLoadException
            ,
        TypeInitializationException
            ,
        VerificationException
            ,
        WeakReferenceException
            ,
        VTableCallsNotSupportedException
            , COMException
    }
}
